# Generated by Django 4.1.7 on 2023-03-25 17:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_status_employee_status_changed'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_type', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('demand_message', models.CharField(max_length=250)),
                ('document', models.ImageField(null=True, upload_to='')),
                ('approver_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver_employee', to='employees.employee')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('receiver_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_employee', to='employees.employee')),
                ('sender_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_employee', to='employees.employee')),
            ],
        ),
    ]
