# Generated by Django 4.1.7 on 2023-03-27 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0005_alter_employee_email_alter_employee_username'),
        ('demands', '0002_demand_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='approver_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_employee', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='receiver_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_employee', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='sender_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_employee', to='employees.employee'),
        ),
    ]
