# Generated by Django 4.1.7 on 2023-03-25 16:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('buy_at', models.DateTimeField(null=True)),
                ('bill_image', models.ImageField(null=True, upload_to='')),
                ('asset_status', models.CharField(max_length=250)),
                ('note', models.CharField(max_length=250)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
        ),
    ]
