# Generated by Django 4.1.7 on 2023-03-25 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('FEMALE', 'F'), ('MALE', 'M'), ('UNKNOWN', 'U')], default='U', max_length=10)),
                ('birth_date', models.DateField(null=True)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('start_date', models.DateField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('join_date', models.DateField(default=datetime.datetime.now)),
                ('note', models.TextField(max_length=250)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
            ],
        ),
    ]
