# Generated by Django 4.1.7 on 2023-03-25 17:05

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_status_employee_status_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=model_utils.fields.StatusField(choices=[('active', 'active'), ('passive', 'passive')], default='active', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
